version: "3"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.31
    ports:
      - "16686:16686"   # Jaeger UI
      - "14268:14268"   # Jaeger collector
      - "14250:14250"   # Jaeger gRPC

  otel-collector:
    image: otel/opentelemetry-collector:0.54.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"     # OTLP gRPC receiver
